# Dictionary of Country Groups

countryGroups = {"Africa": ['South Africa', 'Morocco', 'Tunisia', 'Egypt', 'Libya', 'Ehtiopia', 'Kenya', 'Zambia', 'Botswana', 'Algeria', 'Nigeria', 'Zimbabwe', 'Mozambique', 'Ghana', 'Namibia', 'Uganda', 'Rwanda', 'Cameroon', 'Angola', 'DRC', 'Senegal', 'Malawi', 'Ivory Coast', 'Eswatini', 'Madagascar', 'Sudan', 'Mauritania', 'Cabo Verde', 'Burundi', 'Seychelles', 'Gabon', 'Mayotte', 'Mauritius', 'Tanzania', 'Togo', 'Guinea', 'Lesotho', 'Mali', 'Benin', 'Somalia', 'Congo', 'Burkina Faso', 'South Sudan', 'Equatorial Guinea', 'Djibouti', 'Gambia', 'Eritrea', 'Niger', 'Comoros', 'Guinea-Bissau', 'Liberia', 'Sierra Leone', 'Chad', 'Sao Tome and Principe', 'Saint Helena', 'Western Sahara'],
                 "North America": ['Anguilla', 'Martinique', 'Cura\u00e7ao', 'Aruba', 'Turks and Caicos', 'Cayman Islands', 'Greenland', 'Antigua and Barbuda', 'Bahamas', 'Barbados', 'Belize', 'Canada', 'Costa Rica', 'Cuba', 'Dominican Republic', 'Dominica', 'El Salvador', 'Grenada', 'Guatemala', 'Haiti', 'Honduras', 'Jamaica', 'Mexico', 'Nicaragua', 'Panama', 'Saint Kitts and Nevis', 'Saint Lucia', 'Trinidad and Tobago', 'USA'],
                 "Asia": ['India', 'S. Korea', 'Japan', 'Turkey', 'Vietnam', 'Taiwan', 'Iran', 'Indonesia', 'Malaysia', 'DPRK', 'Israel', 'Thailand', 'Philippines', 'Iraq', 'Hong Kong', 'Singapore', 'Bangladesh', 'Georgia', 'Jordan', 'Pakistan', 'Kazakhstan', 'Lebanon', 'UAE', 'Nepal', 'Mongolia', 'Saudia Arabia', 'Azerbaijan', 'Bahrain', 'Sri Lanka', 'Kuwait', 'Myanmar', 'Cyprus', 'Palestine', 'Qatar', 'Armenia', 'Oman', 'China', 'Brunei', 'Uzbekistan', 'Laos', 'Afghanistan', 'Kyrgyzstan', 'Maldives', 'Cambodia', 'Bhutan', 'Syria', 'Timor-Leste', 'Tajikistan', 'Yemen', 'Macao', ],
                 "Oceania": ['Australia', 'New Zealand', 'French Polynesia', 'New Caledonia', 'Fiji', 'Papua New Guinea', 'Solomon Islands', 'Micronesia', 'Tonga', 'Samoa', 'Marshall Islands', 'Vanuatu', 'Cook Islands', 'Palau', 'Nauru', 'Kiribati', 'Tuvalu', 'Wallis and Futuna', 'Niue'],
                 "Europe": ['Germany', 'France', 'Italy', 'UK', 'Russia', 'Spain', 'Netherlands', 'Poland', 'Austria', 'Portugal', 'Greece', 'Ukraine', 'Belgium', 'Czechia', 'Switzerland', 'Romania', 'Denmark', 'Sweden', 'Serbia', 'Hungary', 'Slovakia', 'Ireland', 'Norway', 'Finland', 'Bulgaria', 'Lithuania', 'Slovenia', 'Croatia', 'Belarus', 'Latvia', 'Estonia', 'Moldova', 'Bosnia and Herzegovina', 'North Macedonia', 'Albania', 'Luxembourg', 'Montenegro', 'Iceland', 'Malta', 'Channel Islands', 'Andorra', 'Isle of Man', 'Faeroe Islands', 'San Marino', 'Liechtenstein', 'Gibraltar', 'Monaco', 'Vatican City'],
                 "South America": ['Brazil', 'Argentina', 'Colombia', 'Chile', 'Peru', 'Bolivia', 'Ecuador', 'Uruguay', 'Paraguay', 'Venequela', 'French Guiana', 'Suriname', 'Guyana', 'Falkland Islands'],
                 "EU": ['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden'],
                 "NATO": ['Albania', 'Belgium', 'Bulgaria', 'Canada', 'Croatia', 'Czechia', 'Denmark', 'Estonia', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Italy', 'Latvia', 'Lithuania', 'Luxembrourg', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Turkey', 'UK', 'USA'],
                 "ASEAN": ['Brunei', 'Cambodia', 'Indonesia', 'Laos', 'Malaysia', 'Myanmar', 'Philippines', 'Singapore', 'Thailand', 'Vietnam'],
                 "OPEC": ['Algeria', 'Angola', 'Equatorial Guinea', 'Gabon', 'Iran', 'Iraq', 'Kuwait', 'Libya', 'Nigeria', 'DRC', 'Saudi Arabia', 'UAE', 'Venezuela'],
                 "G10": ['Belgium', 'Canada', 'France', 'Germany', 'Italy', 'Japan', 'Netherlands', 'Sweden', 'UK', 'USA'],
                 "G20": ['Argentina', 'Australia', 'Brazil', 'Canada', 'China', 'France', 'Germany', 'India', 'Indonesia', 'Italy', 'Japan', 'Mexico', 'S. Korea', 'Russia', 'Saudi Arabia', 'South Africa', 'Turkey', 'UK', 'USA']
                 }
